workspace(name = "minilibx_linux")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# This file will be augmented by .bazelrc.local generated by the Nix flake
# The Nix flake will create a workspace_extra.bzl with library paths

load("//:workspace_deps.bzl", "load_dependencies")
load_dependencies()
